#!/bin/sh

OPTIONS_FILE=$DIAL_SCRIPTS_PATH/"zte_chat_options"

$DIAL_SCRIPTS_PATH/zte_log $0 "OPTIONS_FILE = " $OPTIONS_FILE
$DIAL_SCRIPTS_PATH/zte_log $0 "TELEPHONE = " $TELEPHONE

exec /usr/sbin/chat -v -s						\
	TIMEOUT		3				\
	ABORT		'\nBUSY\r'				\
	ABORT		'\nNO ANSWER\r'			\
	ABORT		'\nRINGING\r\n\r\nRINGING\r'	\
	''		\rAT					\
''		\rAT+CFUN=1					\
OK		ATS0=0				\
	OK		AT+CPIN?				\
	'READY'-"AT+CPIN=\"1234\""-'OK'	AT+CPMS?	\
	OK		AT+CGDCONT=1,\"IP\",\"3gnet\"	\
	''		'ATDT*99#'			\
	CONNECT		''				\
