#!/bin/sh /etc/rc.common
USE_PROCD=1
START=52
start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/aoa_proxy
	procd_set_param respawn
	procd_set_param limits core="unlimited"
	procd_close_instance
}