#!/bin/sh /etc/rc.common

START=97
STOP=10

USE_PROCD=1

start_service() {
	if [ -e /dev/cdc-wdm0 ]
    then
            procd_open_instance
            procd_set_param command /usr/bin/quectel-CM -i "wwan0"
            procd_close_instance
    fi
}
