#!/bin/sh /etc/rc.common

START=96
STOP=10

USE_PROCD=1

start_service() {
	if [ -e /dev/cdc-wdm1 ]
    then
            procd_open_instance
            procd_set_param command /usr/bin/quectel-CM -i "wwan1"
            procd_close_instance
    fi
}
